# config/application.yml

AWS_ACCESS_KEY: "Your-access-key"
AWS_SECRET_KEY: "Your-secret-key"
AWS_BUCKET:     "Your-bucket"
AWS_REGION:     "us-east-1"
SECRET_KEY: 'sk_test_1111xxxxxxxx1111'
PUBLISHABLE_KEY: 'pk_test_1111xxxxxxxx1111'